name: CD / Deploy / main
concurrency: cd-production

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Print tag name
        run: echo ${{github.ref_name}}
        
      - name: Build with Maven
        run: mvn compile
      - name: Package with Maven
        run: mvn package
