name: CD / Deploy / release
concurrency: cd-production

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          
      - name: Print tag name
        run: echo ${REF_TAG:1}
        env:
          REF_TAG: ${{ github.ref_name }}
        
      - name: Build with Maven
        run: mvn compile
      - name: Package with Maven
        run: mvn package
        
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: ${{ secrets.nexus_url }}
          username: ${{ secrets.nexus_username }}
          password: ${{ secrets.nexus_password }}
          format: maven2
          repository: maven-releases
          coordinates: groupId=com.github.vitalibo artifactId=brick-game version=${{ github.ref_name }}
          assets: extension=jar
          filename: ./target/brick-game.jar
        
